#!/usr/bin/env python3
"""Generate a C++ header with the CEngine strings table from the en-US .resw.

Usage: python3 Tools/generate_engine_strings.py

Reads  src/Calculator/Resources/en-US/CEngineStrings.resw
Writes src/MacBridge/EngineStringsData.g.h
"""
import xml.etree.ElementTree as ET
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RESW = REPO_ROOT / "src/Calculator/Resources/en-US/CEngineStrings.resw"
OUTPUT = REPO_ROOT / "src/MacBridge/EngineStringsData.g.h"


def cpp_escape(text: str) -> str:
    return (
        text.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )


def main() -> None:
    tree = ET.parse(RESW)
    entries = []
    for data in tree.getroot().iter("data"):
        name = data.get("name")
        value_node = data.find("value")
        if name is None or value_node is None:
            continue
        entries.append((name, value_node.text or ""))
    entries.sort()

    lines = [
        "// Generated by Tools/generate_engine_strings.py from",
        "// src/Calculator/Resources/en-US/CEngineStrings.resw. Do not edit.",
        "#pragma once",
        "",
        "#include <string_view>",
        "#include <unordered_map>",
        "",
        "namespace MacCalc",
        "{",
        "    inline const std::unordered_map<std::wstring_view, std::wstring_view>& EngineStringsEnUS()",
        "    {",
        "        static const std::unordered_map<std::wstring_view, std::wstring_view> table = {",
    ]
    for name, value in entries:
        lines.append(f'            {{ L"{cpp_escape(name)}", L"{cpp_escape(value)}" }},')
    lines += [
        "        };",
        "        return table;",
        "    }",
        "}",
        "",
    ]
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(entries)} entries to {OUTPUT}")


if __name__ == "__main__":
    main()
